# Generated by Django 2.2.4 on 2019-12-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(default='')),
                ('url', models.TextField(default='NONE')),
                ('part', models.TextField(default='ALL')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
