# Generated by Django 2.2.4 on 2019-12-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.TextField(choices=[('A', 'Active'), ('I', 'Inactive')], db_index=True, default='A'),
        ),
    ]
