# Generated by Django 2.2.4 on 2019-12-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_score_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='url',
            new_name='allURL',
        ),
        migrations.AddField(
            model_name='score',
            name='partURL',
            field=models.TextField(default='NONE'),
        ),
    ]
