# Generated by Django 2.2.4 on 2019-12-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20191218_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_dark',
            field=models.BooleanField(default=False),
        ),
    ]
