# Generated by Django 2.2.4 on 2019-12-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_score_is_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='driveAllURL',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='score',
            name='drivePartURL',
            field=models.TextField(default='NONE'),
        ),
    ]
