# Generated by Django 2.2.4 on 2019-12-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191218_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='priority',
            field=models.IntegerField(default=8),
        ),
    ]
