# Generated by Django 2.2.4 on 2019-09-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='decorColor',
            new_name='decor',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='varImages', to='store.ProductVariant'),
            preserve_default=False,
        ),
    ]
