# Generated by Django 2.2.4 on 2019-09-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190923_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.AddField(
            model_name='product',
            name='decor',
            field=models.TextField(default='white'),
        ),
        migrations.AddField(
            model_name='product',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='shirtColor',
            field=models.TextField(default='white'),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
