# Generated by Django 2.2.4 on 2019-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190923_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cut',
            field=models.TextField(default=''),
        ),
    ]
