# Generated by Django 2.2.4 on 2019-09-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_cut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mainColor',
        ),
    ]
