# Generated by Django 2.2.4 on 2019-09-23 21:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_maincolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('purchased', models.DateTimeField(default=None, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('charge_id', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1)),
                ('quantity', models.IntegerField(default=0)),
                ('size', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.Sale')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
    ]
