# Generated by Django 2.2.4 on 2019-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='isReferral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='referrer',
            field=models.TextField(default=None, null=True),
        ),
    ]
