# Generated by Django 2.2.4 on 2019-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190924_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='isReferral',
        ),
        migrations.AddField(
            model_name='sale',
            name='shipMethod',
            field=models.TextField(default=None, null=True),
        ),
    ]
