# Generated by Django 2.2.4 on 2019-09-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190924_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='orderID',
            field=models.TextField(default=None, null=True),
        ),
    ]
