# Generated by Django 2.1.5 on 2019-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190306_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productimage',
            name='filename',
            field=models.TextField(default='noimage.png'),
        ),
    ]
